name: CI Build and QEMU Test for armhf

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install cross-compiler and qemu
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-linux-gnueabihf qemu-user make

      - name: Build (static linking)
        run: make

      - name: Run QEMU-based tests
        continue-on-error: true
        run: |
          for bin in bin/*; do
            echo "Running $bin under qemu-arm..."
            qemu-arm -L /usr/arm-linux-gnueabihf "$bin"
            echo ""
          done

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: test-binaries-armhf
          path: bin/
