name: Build ARMHF Binaries

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ARMHF cross compiler
        run: sudo apt-get update && sudo apt-get install -y gcc-arm-linux-gnueabihf make

      - name: Build all targets
        run: make

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: armhf-binaries
          path: bin/
